
[functions.enviar-confirmacion-pedido]
enabled = true
verify_jwt = false
import_map = "./functions/enviar-confirmacion-pedido/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/enviar-confirmacion-pedido/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/enviar-confirmacion-pedido/*.html" ]

[functions.responder-mensaje]
enabled = true
verify_jwt = false
import_map = "./functions/responder-mensaje/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/responder-mensaje/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/responder-mensaje/*.html" ]
